# Simple GitLab CI/CD Pipeline for SwarmApp
# Basic build and test pipeline

stages:
  - build
  - test

variables:
  REGISTRY: $CI_REGISTRY
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

# Build stage - Compile the application
build:
  stage: build
  image: gcc:11
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - build/swarm-app
    expire_in: 1 hour
  only:
    - main
    - develop
    - merge_requests

# Test stage - Run unit tests
test:
  stage: test
  image: gcc:11
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake libgtest-dev libgmock-dev
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make test-swarm-app
    - ./test-swarm-app
  only:
    - main
    - develop
    - merge_requests

# Build Docker image (optional)
package:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f docker/Dockerfile -t $REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG .
    - docker push $REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
  only:
    - main
    - develop
    - tags
