version: '3.8'

services:
  web:
    image: swarm-app:latest
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - swarm-network

networks:
  swarm-network:
    driver: overlay
